### PR TITLE
docs: Update sphinx documentation

### PR DESCRIPTION
**Pull request by dataJSA**
This PR updates the pyro-risks repository sphinx documentation: 

- Add source files for building documentation from the class/method/function docstrings
- Add source files for building documentation for the publicly available dataset we used 
- Fix typo and wrong hyperlinks links in the README and CONTRIBUTING files 

Here is how it looks like:

image
 
I have only documented the datasets we used in the latest versions of the score, It's a start I have no doubt that we will iterate on that !

### CODE REVIEW

**Comment by chloeskt** [comment]
Hi @dataJSA thank you for this PR ! It seems that there is an issue with the tests, can you check that ? :)

**Comment by chloeskt** [comment]
Hi @dataJSA thank you for this PR ! It seems that there is an issue with the tests, can you check that ? :)

**Comment by chloeskt** [comment]
hey @dataJSA, if you rebase on master and solve the conflict (which is due to black usage). I wanted to do it but since you fork the repo, I would have to open a new PR with no conflict, it's easier if you do it (so that I don't need to clone your fork) :)

**Comment by dataJSA** [comment]
Thanks @chloeskt, I will do that !

**Pull request closed without merging**
