### PR TITLE
use black for formatting and fix test test_prepare_dataset

### PR DESCRIPTION
**Pull request by chloeskt**
This PR aims at fixing the issue #8 which concerns black formatting. Basically I have applied black on all the files in our repo. 

Also I fixed a minor bug in the tests for the function `test_prepare_dataset`, this will allow the CI to pass on @dataJSA other PR and will allow us to merge it ! 

As always, reviews are welcome 🤗

### CODE REVIEW

**Review by dataJSA — COMMENTED** [review]
Thanks for your PR @chloeskt  ! 

I just took a look at the `test/test_models.py`,  just to be sure I understand it correctly the test was failing due to the ordering of the columns ?

**Review by dataJSA — CHANGES_REQUESTED** [review]
I think we should add a black linting check to the CI for enforcing the change for all the upcoming commits.  Could you just add the following  github action 

```yaml
name: black

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
```

in the workflow file https://github.com/pyronear/pyro-risks/blob/8a66bd1f46028caf4464f6e2ae50e5cba99ef19d/.github/workflows/main.yml#L90

**Comment by chloeskt** [comment]
Good idea @dataJSA ! Thanks ! I've added it. And yes, the order of the column was mixed up which made the tests fail

**Review by dataJSA — CHANGES_REQUESTED** [review]
Thanks @chloeskt ,

I just realized I gave you a code snippet for defining a linting workflow but we only need to add an other job, sorry for that !

You should only  paste this part at the end of the `main.yml` and the CI should run properly

```yaml
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
```
You can delete this part which is already defined at the top of the file

```yaml
name: black

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
```

**Comment by chloeskt** [comment]
Done @dataJSA thank you very much :)

**Review by dataJSA — APPROVED** [review]
Thanks @chloeskt !

**Pull request merged**
