### PR TITLE
feat: add ERA5Land dataset

### PR DESCRIPTION
**Pull request by chloeskt**
Hello, this PR aims at adding ERA5Land dataset, available at https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview, using https://pypi.org/project/cdsapi/ and API key.

UPDATE: I add in the release the following file `test_data_ERA5_2018.nc` which is a subset of the bigger ERA5 dataset. Now tests are way more faster, thanks @dataJSA !

### CODE REVIEW

**Comment by chloeskt** [comment]
On my local computer, all tests passed, here I get "Error: Process completed with exit code 137.", probably due to exceeding RAM ? 

Capture d’écran 2020-11-16 à 19 29 05

**Comment by GHCamille** [comment]
I didn't complete the testing because my computer crashed but I had an issue with the /pyro_risks/datasets/__init__.py file because there was a missing line :
```
from .ERA5 import *
```

**Comment by miltminz** [comment]
Is the loading test which takes too much time?

**Comment by chloeskt** [comment]
> I didn't complete the testing because my computer crashed but I had an issue with the `/pyro_risks/datasets/__init__.py` file because there was a missing line :
> 
> ```
> from .ERA5 import *
> ```

That's weird. It doesn't cause any troubles on my local computer.

**Comment by chloeskt** [comment]
> Is the loading test which takes too much time?

This tests takes around 15min: 
```
def test_era5land(self):
    ds = ERA5.ERA5Land()
    self.assertIsInstance(ds, pd.DataFrame)
```

**Comment by dataJSA** [comment]
@chloeskt 

The quick fix for speeding up the test would be to 
- download a subset of the ERA5Land datasets (~1 month) and attached it to the release a new release 
- use the new URL as patch for `source_path = cfg.FR_ERA5LAND_FALLBACK` in the test so that the source_path of the class  points to the smallest file.

**Comment by miltminz** [comment]
Yes, I do agree too with the idea of loading a smaller dataset for the unit tests, 30 minutes waiting for the tests to pass it's a bit too much

**Comment by chloeskt** [comment]
Alright, I agree with you! Going to do that @dataJSA 👍

**Comment by dataJSA** [comment]
@chloeskt nice, there is just 3 docstrings issues flag left, you can see them if you go on the Codacy details and click on resolve). Don't bother with the fourth one (setup.py) the issue seems to be related to a bug in the quality assessment package use by Codacy (https://github.com/PyCQA/bandit/issues/333)

**Comment by chloeskt** [comment]
Done @dataJSA

**Comment by chloeskt** [comment]
@dataJSA for the 3rd issue, @GHCamille had a problem without this line therefore I added it even if it does not seem to be useful

**Comment by chloeskt** [comment]
@dataJSA I'm not sure to understand what's the problem in the `ERA5.py` script with the blank line, whatever I try it seems not to work, however it seems to follow the guidelines given here https://www.python.org/dev/peps/pep-0257/ 
Do you have an idea ?

**Comment by chloeskt** [comment]
Btw @dataJSA  now the tests failed, due to this: 
Capture d’écran 2020-11-16 à 23 36 02

Since you implemented the corresponding function and I did not modifiy the files, do you know why ?

**Comment by dataJSA** [comment]
> @dataJSA I'm not sure to understand what's the problem in the `ERA5.py` script with the blank line, whatever I try it seems not to work, however it seems to follow the guidelines given here https://www.python.org/dev/peps/pep-0257/
> Do you have an idea ?

> @dataJSA for the `'.ERA5.*' imported but unused (F401)` issue, @GHCamille had a problem without this line therefore I added it. UPDATE: this is used, cf `example_ERA5_FIRMS.py`. I think that Codacy had its limits 😅

@chloeskt It also happened to me I couldn't fix an issue (D213) last time. You totally right at least we need to look how to configure Codacy a bit better or get ride of it.

**Comment by dataJSA** [comment]
> Moreover I don't like to use * when doing imports, it imports everything and can get things messed up. Should we rather remove the * and import functions and classes explicitly ? I believe that it will solve this issue 😄

`import *` is view as a bad practice since the by default python import all the objects in the module.
However it is fine to do so if you configure the list of objects that will be exported from the module  `__all__ ` variable. 
For instance with setting `__all__ = ["ERA5Land"]`  in `ERA5.py` the `from .ERA5 import *` in the init file will only import the ERA5 class

**Review by dataJSA — APPROVED** [review]

**Comment by chloeskt** [comment]
Thank you @dataJSA for all these information !

**Pull request merged**
