### PR TITLE
Viirs proximity

### PR DESCRIPTION
**Pull request by chloeskt**
This PR aims at:

- adding NASA FIRMS VIIRS dataset and class to clean it
- use a way more efficient algorithm to merge datasets by proximity (thanks to KDTree). This allows also to merge ERA5/VIIRS with FWI, to get, for 2019, around 35000 lines of data (one line = one point on one day)
- update unittests accordingly 
- remove the TODOs left by @dataJSA (I checked with him, they should have been removed)

As always, all reviews are welcome 😄

### CODE REVIEW

**Review by dataJSA — CHANGES_REQUESTED** [review]
Thanks for the PR @chloeskt, it is awesome  ! 
There is no unittest  for `pyro_risks/models/xgb_classifier.py` and some cases that are not covered since you have updated  the `pyro_risks/datasets/nasa_wildfires.py` module

**Comment by chloeskt** [comment]
> Thanks for the PR @chloeskt, it is awesome !
> There is no unittest for `pyro_risks/models/xgb_classifier.py` and some cases that are not covered since you have updated the `pyro_risks/datasets/nasa_wildfires.py` module

Hi @dataJSA, I deleted all models file since it was not relevant for this PR (my bad). For the tests, I guess we would need to add test data in the data release to test the cases that are missed since they related to different files format if you all details 😄

**Comment by chloeskt** [comment]
Hi @dataJSA I've added in the release mock test files which allow to write new tests for various file formats (csv, json and xlsx). Now the coverage is higher 😄

**Comment by dataJSA** [comment]
> Hi @dataJSA I've added in the release mock test files which allow to write new tests for various file formats (csv, json and xlsx). Now the coverage is higher 😄

Thanks for your PR @chloeskt  !

**Review by dataJSA — APPROVED** [review]

**Pull request merged**
