### PR TITLE
chore: Added MacOS & Windows build jobs

### PR DESCRIPTION
**Pull request by frgfm**
This PR adds CI jobs to ensure that the project builds on the most common OS.

### CODE REVIEW

**Comment by frgfm** [comment]
I think I need some help here: I managed to get the MacOS build working, but I'm still having issues on Windows (cf. https://github.com/pyronear/pyro-risks/pull/17/checks?check_run_id=1442323073)

Those of you running on Windows, how did you install spatialindex (for geopandas to work)? Did you use conda?

cc @dataJSA @chloeskt @miltminz @GHCamille @Val38DataScience

**Comment by dataJSA** [comment]
> I think I need some help here: I managed to get the MacOS build working, but I'm still having issues on Windows (cf. https://github.com/pyronear/pyro-risks/pull/17/checks?check_run_id=1442323073)
> 
> Those of you running on Windows, how did you install spatialindex (for geopandas to work)? Did you use conda?
> 
> cc @dataJSA @chloeskt @miltminz @GHCamille @Val38DataScience

@frgfm I only installed the geopandas package on MacOS and on Linux, but installing with pip on Windows causes issues due to C dependencies 

image

Normally installing with `conda install --channel conda-forge geopandas` should work

**Comment by frgfm** [comment]
@dataJSA I tried your suggestion and many other conda commands I found online, but none seems to work

If one of you guys have something working on windows, I'd be keen to try!

**Comment by chloeskt** [comment]
Hi @frgfm, unfortunately I only use Linux and MacOS ... Did you try what is proposed [here](https://stackoverflow.com/questions/56958421/pip-install-geopandas-on-windows)  ?

**Comment by frgfm** [comment]
@chloeskt thing is that the page owner hid the download behind some javascript, so I'm unable to script the download of the wheel files...
But I'm not the best at web development so I'm not sure. Perhaps, for Windows, we can only say in the readme that people need to install geopandas and get it to work as a prerequisite

**Comment by chloeskt** [comment]
yes I agree @frgfm

**Comment by dataJSA** [comment]
@frgfm ok, let's do that, I will had the conda command to the readme

**Comment by frgfm** [comment]
@dataJSA I think it will be better to redirect to the geopandas official installation instructions, because the command you suggested is not working on the CI for Windows :/

**Review by chloeskt — APPROVED** [review]

**Pull request merged**
